apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commoncal.fullname" . }}
  labels:
    {{- include "commoncal.labels" . | nindent 4 }}
data:
  APP_ENV: production
  BIND_ADDRESS: 0.0.0.0:3000
  APP_ORIGIN: {{ required "config.appOrigin is required" .Values.config.appOrigin | quote }}
  DATABASE_PATH: /app/data/commoncal.sqlite
