{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sqlite-console-deny-all
  labels:
    {{- include "commoncal.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      commoncal.io/role: sqlite-console
  policyTypes:
    - Ingress
    - Egress
{{- end }}
