# Flux image repository for calendar-mcp
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: image-repository-mcp
  namespace: flux-system
spec:
  image: ghcr.io/david-hajnal/calendar-mcp
  provider: ghcr
